# !/usr/bin/env python
# coding=utf-8

BROWSER = 'browser_type'
BASE_URL = 'base_url'
COPY = 'copy'
INTERACTIVE = 'interactive'
INTER_QUEUE = 'inter_queue'
MSG_QUEUE = 'msg_queue'
JOB_ID = 'jobid'
LOG_FILE = 'log_file'
MODULE = 'module'
MODULE_SCRIPT = 'module_script'
NUM_THREADS = 'num_threads'
PASSWORD = 'password'
PAUSE = 'pause'
TEST_DIR = 'test_dir'
TEST_NAME = 'test_name'
USER = 'user'
WWW_DIR = 'www_dir'
